## SPDX-FileCopyrightText: 2024 M. Shulhan <ms@kilabit.info>
##
## SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
path = ["_wui/**"]
SPDX-FileCopyrightText = "2021 Shulhan <ms@kilabit.info>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["_AUR/**", "_example/**", ".gitignore", ".gitmodules", "go.sum"
  , "README.md", "_www/**", "testdata/**"]
SPDX-FileCopyrightText = "2022 Shulhan <ms@kilabit.info>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [".golangci.yaml", "_bin/.gitignore", "_coverage/.gitignore"
  , "_ops/**", "_tour/**", "internal/cmd/www-awwan/memfs.go"]
SPDX-FileCopyrightText = "2023 Shulhan <ms@kilabit.info>"
SPDX-License-Identifier = "GPL-3.0-or-later"
